name: Baton
main: Nerahikada\Baton
api: [3.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8 3.0.0-ALPHA9]
version: 1
load: POSTWORLD
author: ねらひかだ
website: https://twitter.com/Nerahikada

commands:
  baton:
    description: "警棒プラグインのコマンドです"
    usage: "/baton help"