name: Baton
main: Nerahikada\Baton
version: 1.2.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: ねらひかだ
description: 警棒プラグイン
website: https://github.com/Nerahikada/Baton
commands:
  baton:
    description: "警棒プラグインのコマンド"
    usage: "/baton help"